# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71faf58d3145be02fb90374485fc82c6b4f4bc040e89f13a3367e88727df13861b27b47c6eabafa3fc4c10eef6ae83a9b4b5140ae7896f5bf0970ff8ee6ad6b2

test:
  secret_key_base: d2fc575e23f33423d20c5ac3751311a5426926b3e6a65f13763c0e60e7acb1399cae71675afd2632ab6a9c9700b7b29f9cc7d32bc5611f8f741d7ad87ec0e6d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
